[meta]
  title = "Next.js Text-to-Speech Starter"
  description = "Get started using Deepgram's Text-to-Speech with this Next.js demo app"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "TTS"
  language = "JavaScript"
  framework = "Next"

[build]
  command = "npm install"

[config]
  sample = "sample.env.local"
  output = ".env.local"

[post-build]
  message = "Run `npm run dev` to get up and running locally."
